# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "tty-prompt", "~> 0.23.1"

gem "colorize", "~> 0.8.1"

gem "artii", "~> 2.1"

gem "lolize", "~> 0.0.3"

gem "tty-font", "~> 0.5.0"

gem "tty-progressbar", "~> 0.18.2"

gem "tty-box", "~> 0.7.0"

gem "pastel", "~> 0.8.0"
